# Generated by Django 6.0.1 on 2026-01-27 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contact_hash",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
    ]
