# Generated by Django 6.0.1 on 2026-01-27 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_contact_contact_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_hash",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
