# Generated by Django 6.0.1 on 2026-01-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_contact_contact_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="contact_hash",
        ),
    ]
